### PR TITLE
Safe check for possible non-existing object

### PR DESCRIPTION
**Pull request by BroHammie**

### CODE REVIEW

**Comment by esjewett** [comment]
Wouldn't it be enough to do `d3_transitionInheritId != undefined`?

**Comment by mcwillso** [comment]
No because d3_transitionInheritId does not exist anywhere in the code.  http://stackoverflow.com/questions/11380283/how-can-i-compare-a-non-existing-javascript-object-to-undefined-without-getting

**Comment by esjewett** [comment]
I see. In that case this will never evaluate as true, will it? So the if statement can just be removed and we leave only the else branch?

Or we could bring in the transition object definition from d3. Either would be fine with me.

Context: This is a copy of d3's internal brush code and I just did the minimum to get it working. That didn't include looking at transition functionality.

**Comment by mcwillso** [comment]
I wasn't sure if bringing in the definition might override it. 

This will evaluate to true if d3_transitionInheritId is defined, which in my use case, it will always be false but perhaps for others it may be true.

**Comment by esjewett** [comment]
It will never be true unless we copy it into the library. It's an object that is only ever defined internal to d3.

Personally, I don't need the transitions and won't be able to test them, so if you want to update this pull request to just remove the whole statement, just leaving the contents of the `else` clause, I'll merge it.

Thanks!

**Comment by esjewett** [comment]
I lost track of this. Was this completed? Thanks!

**Comment by mcwillso** [comment]
Yes this was completed. Just waiting to get merged.

**Comment by esjewett** [comment]
Sorry to drop the ball. Will merge now. Thanks!

**Pull request merged**
